# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chaoyi Zhu(朱超逸)
title: PhD Student in TU Delft
email: c.zhu-2@tudelft.nl
website: chaoyitud.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: chaoyitud
googlescholar_username: F2TIc-wAAAAJ
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll


about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Chaoyi Zhu, a PhD student in TU Delft. My current research interests include: attacks and defenses in federated learning and adversarial machine learning.

content:
  - title: Publications
    layout: text
    content: |
      *Zhu, C.*, Chen, Z., Zhao, R., Wang, J., & Yan, R. (2021). Decoupled feature-temporal CNN: Explaining deep learning-based machine health monitoring. IEEE Transactions on Instrumentation and Measurement, 70, 1-13.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Beihang University
        caption: 2017 - 2021
        description: BSc Measuring and Control Technology and Instrumentation
      - layout: left
        title: Delft University of Technology
        caption: 2021 - 2023
        description: MSc Computer Engineering
      - layout: left
        title: Delft University of Technology
        caption: 2023 - now
        description: PhD Student Computer Science

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - My favorite anime is Fullmetal Alchemist (鋼の錬金術師).
      - My favorite game is Yu-Gi-Oh!(遊☆戯☆王) Master Duel. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
