# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chaoyi Zhu(朱超逸)
title: PhD Student in TU Delft
email: c.zhu-2@tudelft.nl | zhuchaoyibuaa@gmail.com
website: chaoyitud.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: chaoyitud
googlescholar_username: F2TIc-wAAAAJ
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll


about_profile_image: images/profile.jpeg
about_content: >
  Hi, I'm Chaoyi Zhu, a PhD student at TU Delft. My current research interests include attacks and defenses in federated learning and watermarks in large language models.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: Delft University of Technology
        caption: "2023 - now"
        description: "PhD Student in Computer Science"
      - layout: left
        title: Delft University of Technology
        caption: "2021 - 2023"
        description: "MSc Computer Engineering (cum laude, Overall GPA: 9/10)"
      - layout: left
        title: Beihang University
        caption: "2017 - 2021"
        description: "BSc Measurement and Control Technology and Instrumentation (Overall GPA: 90/100)"

  - title: Publications
    layout: text
    content: |
      - **C. Zhu**, J. Galjaard, et al. "Duwak: Dual Watermarks in Large Language Models", (ACL ARR 2024 Under Review).
      - **C. Zhu**, J. Tang, et al. "Quantifying and Mitigating Privacy Risks for Tabular Generative Models", (PETS 2024 Under Review).
      - **C. Zhu**, S. Roos, and L. Y. Chen. "LeadFL: Client Self-defense Against Model Poisoning in Federated Learning." In International Conference on Machine Learning, pp. 43158-43180. PMLR, 2023.
      - **C. Zhu**, Z. Chen, et al." Decoupled Feature-Temporal CNN: Explaining Deep Learning-Based Machine Health Monitoring." IEEE Transactions on Instrumentation and Measurement 70 (2021): 1-13.

  - title: Industry Cooperation
    layout: list
    content:
      - layout: left
        title: IBM Research
        caption: "07/2023 – present"
        description: "Dual Watermarks in Large Language Models"
      - layout: left
        title: Tata Steel Europe
        caption: "07/2023 – present"
        description: "Multimodal Machine Learning Models for Predicting Mechanical Properties of Steel"
      - layout: left
        title: BlueGen.ai
        caption: "07/2023 – present"
        description: "Quantifying and Mitigating Privacy Risks for Tabular Generative Models"

  - title: Internship
    layout: list
    content:
      - layout: left
        title: "Institute for Infocomm Research, A*STAR, Singapore (Remote)"
        caption: "07/2020 – 09/2020"
        description: "Research Assistant"
      - layout: left
        title: "Distributed Systems, Dept. of Computer Science, TU Delft, Netherlands"
        caption: "07/2022 – 10/2022"
        description: "Research Assistant"

  - title: A Little More About Me
    layout: text
    content: |
      - My favorite anime is Fullmetal Alchemist (鋼の錬金術師).
      - My favorite game is Yu-Gi-Oh! (遊☆戯☆王) Master Duel.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
