# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chaoyi Zhu(朱超逸)
title: PhD Student in TU Delft
email: c.zhu-2@tudelft.nl
website: chaoyitud.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: chaoyitud
googlescholar_username: F2TIc-wAAAAJ
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll


about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Chaoyi Zhu, a PhD student in TU Delft. My current research interests include: attacks and defenses in federated learning and adversarial machine learning.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Beihang University
        caption: 2017 - 2021
        sub_title: BSc Measuring and Control Technology and Instrumentation
      - layout: left
        title: TU Delft
        caption: 2021 - 2023
        sub_title: MSc Computer Engineering
      - layout: left
        title: TU Delft
        caption: 2023 -
        sub_title: PhD Student Computer Science

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
